import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter } from '../components/contract';
import { Main } from '@/components/Main';
import { Button } from '@/components/Button';
import { Footer } from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ padding: '1rem' }}>
        <ConnectButton />
      </header>

      <Main>
        <GetGreeter />
        <SetGreeter />

      </Main>
      <Footer>
        <Button>connect wallet</Button>
        <Button isGhost>wtf is tamiko?</Button>
      </Footer>
    </>
  );
}
